/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VasusStoryRouteImport } from './routes/vasus-story'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PreMarriageRouteImport } from './routes/pre-marriage'
import { Route as ChildProtectionRouteImport } from './routes/child-protection'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesStoryIdRouteImport } from './routes/stories/$storyId'

const VasusStoryRoute = VasusStoryRouteImport.update({
  id: '/vasus-story',
  path: '/vasus-story',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PreMarriageRoute = PreMarriageRouteImport.update({
  id: '/pre-marriage',
  path: '/pre-marriage',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildProtectionRoute = ChildProtectionRouteImport.update({
  id: '/child-protection',
  path: '/child-protection',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdRoute = StoriesStoryIdRouteImport.update({
  id: '/stories/$storyId',
  path: '/stories/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/child-protection': typeof ChildProtectionRoute
  '/pre-marriage': typeof PreMarriageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/vasus-story': typeof VasusStoryRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/child-protection': typeof ChildProtectionRoute
  '/pre-marriage': typeof PreMarriageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/vasus-story': typeof VasusStoryRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/child-protection': typeof ChildProtectionRoute
  '/pre-marriage': typeof PreMarriageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/vasus-story': typeof VasusStoryRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/child-protection'
    | '/pre-marriage'
    | '/sitemap.xml'
    | '/support'
    | '/vasus-story'
    | '/stories/$storyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/child-protection'
    | '/pre-marriage'
    | '/sitemap.xml'
    | '/support'
    | '/vasus-story'
    | '/stories/$storyId'
  id:
    | '__root__'
    | '/'
    | '/child-protection'
    | '/pre-marriage'
    | '/sitemap.xml'
    | '/support'
    | '/vasus-story'
    | '/stories/$storyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChildProtectionRoute: typeof ChildProtectionRoute
  PreMarriageRoute: typeof PreMarriageRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  VasusStoryRoute: typeof VasusStoryRoute
  StoriesStoryIdRoute: typeof StoriesStoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vasus-story': {
      id: '/vasus-story'
      path: '/vasus-story'
      fullPath: '/vasus-story'
      preLoaderRoute: typeof VasusStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-marriage': {
      id: '/pre-marriage'
      path: '/pre-marriage'
      fullPath: '/pre-marriage'
      preLoaderRoute: typeof PreMarriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child-protection': {
      id: '/child-protection'
      path: '/child-protection'
      fullPath: '/child-protection'
      preLoaderRoute: typeof ChildProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId': {
      id: '/stories/$storyId'
      path: '/stories/$storyId'
      fullPath: '/stories/$storyId'
      preLoaderRoute: typeof StoriesStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChildProtectionRoute: ChildProtectionRoute,
  PreMarriageRoute: PreMarriageRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  VasusStoryRoute: VasusStoryRoute,
  StoriesStoryIdRoute: StoriesStoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
